[tool.black]
line-length = 120
include = '\.pyi?$'
extend-exclude = ".vscode/.*"

[tool.isort]
profile = "black"
extend_skip = [".vscode"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
